version: '3.4'

services:
  teuscontroleapi:
    image: ${DOCKER_REGISTRY-}teuscontroleapi
    build:
      context: .
      dockerfile: TeusControleApi/Dockerfile
    depends_on: 
      - database
    ports:
      - "8000:443"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    image: mysql:8.0.22
    container_name: mysqldb
    ports:
      - '3306:3306'
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: hw8vup5e
      MYSQL_USER: teus
      MYSQL_PASSWORD: hw8vup5e
      MYSQL_DATABASE: teuscontroledb
volumes:
  db-volume: