name: teus_controle_ui
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.5.0
  pdf: ^3.8.1
  printing: ^5.9.1
  flutter_secure_storage: ^5.0.2
  mask_text_input_formatter: ^2.3.0
  brasil_fields: ^1.4.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  desktop_window: ^0.4.0 # compativel apenas com desktop
  form_field_validator: ^1.1.0
  jwt_decoder: ^2.0.1
  another_flushbar: ^1.10.29
  shimmer: ^2.0.0
  intl: ^0.17.0
  string_extensions: ^0.6.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/TEUS_CONTROLE_COLORFUL.png
    - assets/images/TEUS_CONTROLE_WHITE.png
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
